import type { Metadata } from "next";
import { Inter } from "next/font/google";
import s from './global.module.scss';
import { ReduxProvider } from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={s.body}>
        <ReduxProvider>
          <main className={s.main}>
            {children}
          </main>
        </ReduxProvider>

      </body>
    </html>
  );
}
