
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './global.css';
import { ReduxProvider } from "@/provider";
import HeaderLine from "@/components/header_line/main";


export const metadata: Metadata = {
  title: "Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body className='body'>
        <ReduxProvider>
          <main className='main'>
            <HeaderLine />

            {children}
          </main>
        </ReduxProvider>

      </body>
    </html>
  );
}
