import type { Metadata } from "next";
import { Inter } from "next/font/google";
import s from './global.module.scss';
import { ReduxProvider } from "@/provider";
import HeaderLine from "@/components/header_line/main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body className={s.body}>
        <ReduxProvider>
          <main className={s.main}>
            <HeaderLine />

            {children}
          </main>
        </ReduxProvider>

      </body>
    </html>
  );
}
